"use strict";
// Copyright (c) 2024 Black Duck Software Inc. All rights reserved worldwide.
Object.defineProperty(exports, "__esModule", { value: true });
exports.BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES = void 0;
var BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES;
(function (BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES) {
    BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES["ALL"] = "ALL";
    BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES["NONE"] = "NONE";
    BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES["BLOCKER"] = "BLOCKER";
    BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES["CRITICAL"] = "CRITICAL";
    BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES["MAJOR"] = "MAJOR";
    BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES["MINOR"] = "MINOR";
    BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES["OK"] = "OK";
    BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES["TRIVIAL"] = "TRIVIAL";
    BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES["UNSPECIFIED"] = "UNSPECIFIED";
})(BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES = exports.BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES || (exports.BLACKDUCKSCA_SCAN_FAILURE_SEVERITIES = {}));
