#################################################################################
#####  Gitlab CI Variables
#################################################################################

.retry:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.only:
  only:
    refs:
      - master
      - main
      - /^release-.*$/

.except:
  except: [ ]

#################################################################################
#####  Gitlab CI Job Implementations
#################################################################################

.build_unit_tests:
  extends:
    - .retry
  image: gcr.io/snps-polaris-ops-prod/ember_cli:3.28.5-node_16.14
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .m2/
  script:
    - cd synopsys-task
    - npm ci
    - npm run all
    - ls
  artifacts:
    paths:
      - coverage/index.html


.code_coverage:
  image: gcr.io/snps-polaris-ops-prod/ember_cli:3.28.5-node_16.14
  script:
    - cd synopsys-task/coverage
    - cat index.html
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/