#################################################################################
#####  Gitlab CI Variables
#################################################################################

.retry:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.only:
  only:
    refs:
      - master
      - main
      - /^release-.*$/

.except:
  except: [ ]

#################################################################################
#####  Gitlab CI Job Implementations
#################################################################################

.build:
  extends:
    - .retry
  image: gcr.io/snps-polaris-ops-prod/ember_cli:3.28.5-node_16.14
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .m2/
  script:
    - cd synopsys-task
    - npm ci
    - npm run format && npm run lint && npm run build && npm run package

.unit_test:
  image: gcr.io/snps-polaris-ops-prod/ember_cli:3.28.5-node_16.14
  script:
    - cd synopsys-task
    - npm ci
    - npm test > unit_test.log
    - cat unit_test.log
  artifacts:
    paths:
      - ./synopsys-task/unit_test.log

.code_coverage:
  image: gcr.io/snps-polaris-ops-prod/ember_cli:3.28.5-node_16.14
  script:
    - cd synopsys-task
    - cat unit_test.log
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

#.changelog:
#  image: node:17-buster-slim
#  extends:
#    - .only
#  before_script:
#    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
#    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/changelog conventional-changelog-conventionalcommits @semantic-release/commit-analyzer @semantic-release/git
#  script:
#    - semantic-release -r https://sig-gitlab.internal.synopsys.com/integrations/synopsys-action
#
#.check_dist:
#  image: gcr.io/snps-polaris-ops-prod/ember_cli:3.28.5-node_16.14
#  before_script:
#    - npm ci
#    - npm run build
#    - npm run package
#  script:
#    - |-
#      if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
#        echo "Detected uncommitted changes after build.  See status below:"
#        git diff
#        exit 1
#      fi