#################################################################################
#####  Gitlab CI Variables
#################################################################################

.retry:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.only:
  only:
    refs:
      - master
      - main
      - /^release-.*$/

.except:
  except: [ ]

#################################################################################
#####  Gitlab CI Job Implementations
#################################################################################

.build_unit_tests:
  extends:
    - .retry
  image: gcr.io/snps-polaris-ops-prod/ember_cli:3.28.5-node_16.14
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .m2/
  script:
    - cd synopsys-task
    - npm ci
    - npm run all
  artifacts:
    paths:
      - synopsys-task/coverage/


.code_coverage:
  image: gcr.io/snps-polaris-ops-prod/ember_cli:3.28.5-node_16.14
  script:
    - cd synopsys-task
    - coverageFile="coverage/index.html"
    - coverageSpan=$(grep -B 1 '<span class="quiet">Lines</span>' $coverageFile | head -n 1)
    - coverageHtml=$(echo "$coverageSpan" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
    - coverageInPercent=$(echo $coverageHtml | sed -n 's/.*<span class="strong">\([0-9.]*%\).*/\1/p' | tr -d ' ')
    - echo "Line Coverage: $coverageInPercent"
  coverage: $coverageInPercent