# Workflow: Checks code coverage for the project. Fails if line coverage is below the required threshold.
name: Check Code Coverage

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Download coverage summary
        uses: actions/download-artifact@v4
        with:
          name: coverage-summary
          path: blackduck-security-task/coverage

      - name: Check coverage threshold
        shell: bash
        run: |
          coverageValue=$(jq -r '.total.lines.pct' blackduck-security-task/coverage/coverage-summary.json)
          echo "Line Coverage: $coverageValue%"
          if (( $(echo "$coverageValue < 90" | bc -l) )); then
            echo "##[error]Line coverage is below 90%"
            PR=$(jq -r .pull_request.number $GITHUB_EVENT_PATH)
            BODY="## Coverage Threshold
            Line Coverage: $coverageValue%"
            CID=$(gh api repos/${{ github.repository }}/issues/$PR/comments --jq '.[] | select(.body|contains("## Coverage Threshold")) | .id' | head -n1)
            if [ -n "$CID" ]; then
              gh api repos/${{ github.repository }}/issues/comments/$CID -X PATCH -f body="$BODY"
            else
              gh api repos/${{ github.repository }}/issues/$PR/comments -f body="$BODY"
            fi
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}